phplint:
  script:
    - composer config -g repo.packagist composer https://packagist.phpcomposer.com
    - composer update overtrue/phplint 
    - ./vendor/bin/phplint
phpmd:
  script:
    - php phpmd.phar ./ text phpmd.xml --exclude vendor,tests